### PR TITLE
feat: convert to an Analyzer

### PR DESCRIPTION
**Pull request by ldez**
To ease the integration inside golangci-lint, I converted the `Run` function into an Analyzer.

### CODE REVIEW

**Comment by martialblog** [comment]
@ldez  Really admiring all the work you put into golangci!

**Comment by robinknaapen** [comment]
@ldez thanks for the contribution. We appreciate the effort 🙏

Currently we are in a busy state, since the holidays are around the corner.

I will review this PR and ask a peer to double check it.

That said, this will likely happen next week.

Thanks for being patient.

Best regards and happy holidays (you too @martialblog).

**Review by robinknaapen — APPROVED** [review]

**Comment by robinknaapen** [comment]
@ldez 

LGTM, I've asked a co-worker for a second review

**Review by elwint — APPROVED** [review]
lgtm

**Comment by robinknaapen** [comment]
@ldez 

Thanks for the contribution.

Do you intend to create a PR on golangci-lint, or are we expected to do so?

Kind regards

**Comment by ldez** [comment]
Thank you for merging the PR, I handle the update inside golangci-lint.

**Pull request merged**
